Models/Skill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EduCare.Models
{
    [Table("Skill")]
    public class Skill
    {
        public int Id { get; set; }
        [Required]
        public int? SubjectId { get; set; }
        [Required]
        public int? LevelId { get; set; }
        [Required]
        public int? AffiliationId { get; set; }
        public bool? Status { get; set; }
        public string SkillCode { get; set; }
    }
    [Table("SkillView")]
    public class SkillView
    {
        public int Id { get; set; }
        [Required]
        public bool? Status { get; set; }
        public string Subject { get; set; }
        public string Level { get; set; }
        public string Affiliation { get; set; }
        public string SkillCode { get; set; }
    }
}

Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EduCare.Models;

namespace EduCare.Controllers
{
    public class SkillsController : Controller
    {
        private EducareContext db = new EducareContext();

        // GET: Skills
        public ActionResult Index()
        {
            return View();
        }

       
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SkillView skill = db.SkillView.Find(id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            return View(skill);
        }

       
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Skill skill)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    skill.Status = true;
                    skill.SkillCode = AllProcs.GenerateSkillCode(skill.SubjectId, skill.LevelId, skill.AffiliationId);
                    db.Skills.Add(skill);
                    db.SaveChanges();
                    TempData["Msg"] = "1";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["Msg"] = MyFunctions.HandleMyError(ex);
                    return View(skill);
                }
                
            }

            return View(skill);
        }
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skill skill = db.Skills.Find(id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            return View(skill);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Skill skill)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(skill).State = EntityState.Modified;
                    skill.SkillCode = AllProcs.GenerateSkillCode(skill.SubjectId, skill.LevelId, skill.AffiliationId);
                    db.SaveChanges();
                    TempData["Msg"] = "2";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["Msg"] = MyFunctions.HandleMyError(ex);
                    return View(skill);
                }
                
            }
            return View(skill);
        }
        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SkillView skill = db.SkillView.Find(id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            return View(skill);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Skill skill = db.Skills.Find(id);
            db.Skills.Remove(skill);
            db.SaveChanges();
            TempData["Msg"] = "3";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Skills/Create.cshtml
@model EduCare.Models.Skill

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    System.Data.DataTable subject = EduCare.Models.AllProcs.GetSubject();
    System.Data.DataTable level = EduCare.Models.AllProcs.GetLevel();
    System.Data.DataTable affiliation = EduCare.Models.AllProcs.GetAffiliation();
}

<h4 class="fw-bold mt-3 mb-3"><a href=@Url.Action("Index","Skills") class="back-btn"><i class="fa fa-arrow-left"></i> Create Skill</a></h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="box box-primary small-card">
        <div class="box-body">

            <div class="row">

                <div class="col-sm-4">
                    <div class="form-group">
                        <label class="label-required">Subject</label>
                        <select id="SubjectId" name="SubjectId" class="form-control" required>
                            @for (int i = 0; i < subject.Rows.Count; i++)
                            {
                                <option value="@subject.Rows[i]["Id"].ToString()">@subject.Rows[i]["Name"].ToString()</option>
                            }
                        </select>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <label class="label-required">Level</label>
                        <select id="LevelId" name="LevelId" class="form-control" required>
                            @for (int i = 0; i < level.Rows.Count; i++)
                            {
                                <option value="@level.Rows[i]["Id"].ToString()">@level.Rows[i]["Name"].ToString()</option>
                            }
                        </select>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <label class="label-required">Affiliation</label>
                        <select id="AffiliationId" name="AffiliationId" class="form-control" required>
                            @for (int i = 0; i < affiliation.Rows.Count; i++)
                            {
                                <option value="@affiliation.Rows[i]["Id"].ToString()">@affiliation.Rows[i]["Name"].ToString()</option>
                            }
                        </select>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Views/Skills/Delete.cshtml
@model EduCare.Models.SkillView

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold mt-3 mb-3"><a href=@Url.Action("Index","Skills") class="back-btn"><i class="fa fa-arrow-left"></i>Delete Skill </a></h4>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="box box-primary small-card">
        <div class="box-body">

            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <dl class="dl-horizontal">
                            <dt>Subject</dt>
                            <dd>
                                : @Model.Subject
                            </dd>

                            <dt>Level</dt>
                            <dd>
                                : @Model.Level
                            </dd>

                            <dt>Affiliation</dt>
                            <dd>
                                : @Model.Affiliation
                            </dd>

                            <dt>SkillCode</dt>
                            <dd>
                                : @Model.SkillCode
                            </dd>

                            <dt>Status</dt>
                            <dd>
                                : @if (Model.Status ?? false)
                                {
                                    <span class="label badge-soft-success">Active</span>
                                }
                                else
                                {
                                    <span class="label badge-soft-danger">Inactive</span>
                                }
                            </dd>

                        </dl>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        </div>
    </div>


    

}

Views/Skills/Details.cshtml
@model EduCare.Models.SkillView

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold mt-3 mb-3"><a href=@Url.Action("Index","Skills") class="back-btn"><i class="fa fa-arrow-left"></i> Skill Details</a></h4>

<div class="box box-primary small-card">
    <div class="box-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <dl class="dl-horizontal">

                        <dt>Subject</dt>
                        <dd>
                            : @Model.Subject
                        </dd>

                        <dt>Level</dt>
                        <dd>
                            : @Model.Level
                        </dd>

                        <dt>Affiliation</dt>
                        <dd>
                            : @Model.Affiliation
                        </dd>

                        <dt>SkillCode</dt>
                        <dd>
                            : @Model.SkillCode
                        </dd>

                        <dt>Status</dt>
                        <dd>
                            : @if (Model.Status ?? false)
                            {
                                <span class="label badge-soft-success">Active</span>
                            }
                            else
                            {
                                <span class="label badge-soft-danger">Inactive</span>
                            }
                        </dd>


                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Skills/Edit.cshtml
@model EduCare.Models.Skill

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    System.Data.DataTable subject = EduCare.Models.AllProcs.GetSubject();
    System.Data.DataTable level = EduCare.Models.AllProcs.GetLevel();
    System.Data.DataTable affiliation = EduCare.Models.AllProcs.GetAffiliation();
}

<h4 class="fw-bold mt-3 mb-3"><a href=@Url.Action("Index","Skills") class="back-btn"><i class="fa fa-arrow-left"></i> Edit Skill</a></h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)


    <div class="box box-primary small-card">
        <div class="box-body">
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.SubjectId, htmlAttributes: new { @class = "control-label label-required" })
                        <select id="SubjectId" name="SubjectId" class="form-control" required>
                            @for (int i = 0; i < subject.Rows.Count; i++)
                            {
                                <option value="@subject.Rows[i]["Id"].ToString()">@subject.Rows[i]["Name"].ToString()</option>
                            }
                        </select>
                        <script>$('#SubjectId').val('@Model.SubjectId')</script>
                        @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.LevelId, htmlAttributes: new { @class = "control-label label-required" })
                        <select id="LevelId" name="LevelId" class="form-control" required >
                            @for (int i = 0; i < level.Rows.Count; i++)
                            {
                                <option value="@level.Rows[i]["Id"].ToString()">@level.Rows[i]["Name"].ToString()</option>
                            }
                        </select>
                        <script>$('#LevelId').val('@Model.LevelId')</script>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.AffiliationId, htmlAttributes: new { @class = "control-label label-required" })
                        <select id="AffiliationId" name="AffiliationId" class="form-control"required>
                            @for (int i = 0; i < affiliation.Rows.Count; i++)
                            {
                                <option value="@affiliation.Rows[i]["Id"].ToString()">@affiliation.Rows[i]["Name"].ToString()</option>
                            }
                        </select>
                        <script>$('#AffiliationId').val('@Model.AffiliationId')</script>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label " })
                        <select id="Status" name="Status" class="form-control">
                            <option value="True">Active</option>
                            <option value="False">Inactive</option>
                        </select>
                        <script>$('#Status').val('@Model.Status')</script>
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Views/Skills/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    System.Data.DataTable dt2 = EduCare.Models.AllProcs.GetTableData("SkillView");
    var s = TempData["Msg"];
    if (s == null)
    {
        s = 0;
    }
}
<div class="msg-alert">
    @if (s.ToString() == "2")
    {
        <div class="alert alert-warning alert-dismissible" style="background-color: #e5bb79!important">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="color: white; opacity: 1; font-size: 25px;">×</button>
            Data Updated!
        </div>
    }
    else if (s.ToString() == "3")
    {
        <div class="alert alert-danger alert-dismissible" style="background-color: #cd6f64!important;">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="color: white; opacity: 1; font-size: 25px;">×</button>
            Data Deleted!
        </div>
    }
    else if (s.ToString() == "1")
    {
        <div class="alert alert-success alert-dismissible" style="background-color: #4da97f!important">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="color: white; opacity: 1; font-size: 25px;">×</button>
            Data Saved!
        </div>
    }
</div>


<h3 class="fw-bold" style="margin-top:0;">Skills</h3>


<div class="box box-primary">
    <div class="box-body">

        <div class="row">
            <div class="col-sm-3">
                <div class="form-group">
                    <a type="button" href="@Url.Action("Create","Skills")" class="btn btn-default">Add Skill</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="form-group table-responsive">
                    <table class="table table-bordered table-condensed table-striped text-center text-nowrap myDataTable">
                        <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>SkillCode</th>
                                <th>Subject</th>
                                <th>Level</th>
                                <th>Affiliation</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @for (int i = 0; i < dt2.Rows.Count; i++)
                            {
                                int id = Convert.ToInt32(dt2.Rows[i]["Id"].ToString());
                                <tr>
                                    <td>@(i+1)</td>
                                    <td> @dt2.Rows[i]["SkillCode"].ToString()</td>
                                    <td> @dt2.Rows[i]["Subject"].ToString()</td>
                                    <td> @dt2.Rows[i]["Level"].ToString()</td>
                                    <td> @dt2.Rows[i]["Affiliation"].ToString()</td>
                                    <td>
                                        @if (Convert.ToBoolean(dt2.Rows[i]["Status"].ToString()))
                                        {


                                            <span class="label badge-soft-success">Active</span>
                                        }
                                        else
                                        {
                                            <span class="label badge-soft-danger">Inactive</span>
                                        }
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Skills", new { id = id})"><i class="fa fa-edit bg-warning"></i></a>
                                        <a href="@Url.Action("Details", "Skills", new { id = id})"><i class="fa fa-eye bg-success"></i></a>
                                        <a href="@Url.Action("Delete", "Skills", new { id = id})"><i class="fa fa-trash bg-danger"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>


                    </table>
                </div>
            </div>
        </div>
    </div>
</div>