Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EduCare.Models
{
    [Table("Client")]
    public class Client
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Branch { get; set; }
        [Required]
        [Display(Name = "Contact No.")]
        public string ContactNo { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Address { get; set; }

        [Display(Name = "Country")]
        public int? CountryId { get; set; }
        [Required]
        [Display(Name = "State")]
        public int? StateId { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        [Display(Name = "Pincode")]
        public int? Pincode { get; set; }
        [Required]
        public string Website { get; set; }
        public Boolean? Status { get; set; }
        [Display(Name = "Billing Address")]
        public string BillingAddress { get; set; }
        [Display(Name="Country")]
        public int? BillingCountryId { get; set; }
        [Display(Name = "State")]
        public int? BillingStateId { get; set; }
        [Display(Name = "City")]
        public string BillingCity { get; set; }
        [Display(Name = "Pincode")]
        public int? BillingPincode { get; set; }
        [Display(Name = "Email")]
        public string BillingEmail { get; set; }
        [Display(Name = "Phone No.")]
        public string BillingPhoneNo { get; set; }
        [Display(Name = "GST No")]
        public string GSTNo { get; set; }
        [Display(Name = "Payment Terms")]
        public int? PaymentTermId { get; set; }
        [Display(Name = "Terms & Conditions")]
        public string TAndC { get; set; }
    }

    //Grid Table 


    [Table("ContactPerson")]
    public class ContactPerson
    {
        public int Id { get; set; }
        public int? ClientId { get; set; }
        public string Name { get; set; }
        public int? DesignationId { get; set; }
        public int? DepartmentId { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string WhatsAppNo { get; set; }
    }


    [Table("ClientView")]
    public class ClientView
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Branch { get; set; }
        [Required]
        [Display(Name = "Contact No.")]
        public string ContactNo { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Address { get; set; }

        [Display(Name = "Country")]
        public int? CountryId { get; set; }
        [Required]
        [Display(Name = "State")]
        public int? StateId { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        [Display(Name = "Pincode")]
        public int? Pincode { get; set; }
        [Required]
        public string Website { get; set; }
        public Boolean? Status { get; set; }
        [Display(Name = "Billing Address")]
        public string BillingAddress { get; set; }
        [Display(Name = "Country")]
        public int? BillingCountryId { get; set; }
        [Display(Name = "State")]
        public int? BillingStateId { get; set; }
        [Display(Name = "City")]
        public string BillingCity { get; set; }
        [Display(Name = "Pincode")]
        public int? BillingPincode { get; set; }
        [Display(Name = "Email")]
        public string BillingEmail { get; set; }
        [Display(Name = "Phone No.")]
        public string BillingPhoneNo { get; set; }
        public string GSTNo { get; set; }
        [Display(Name = "Payment Terms")]
        public int? PaymentTermId { get; set; }
        [Display(Name = "Terms & Conditions")]
        public string TAndC { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        [Display(Name="Billing Country")]
        public string BillingCountryName { get; set; }
        [Display(Name = "Billing State")]
        public string BillingStateName { get; set; }
        public string PaymentTerms { get; set; }
        public string Designation { get; set; }

    }

    //[Table("ContactPersonView")]
    //public class ContactPersonView
    //{
    //    public int Id { get; set; }
    //    public int? ClientId { get; set; }
    //    public string Name { get; set; }
    //    public int? DesignationId { get; set; }
    //    public int? DepartmentId { get; set; }
    //    public string Email { get; set; }
    //    public string ContactNo { get; set; }
    //    public string WhatsAppNo { get; set; }
    //    public string Designation { get; set; }
    //    public string Department { get; set; }
    //}
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EduCare.Models;
using Newtonsoft.Json;

namespace EduCare.Controllers
{
    public class ClientsController : Controller
    {
        private EducareContext db = new EducareContext();

        // GET: Client
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientView Client = db.ClientView.Find(id);
            if (Client == null)
            {
                return HttpNotFound();
            }
            return View(Client);
        }

        
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Client Client)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Client.Status = true;
                    db.Client.Add(Client);
                    db.SaveChanges();

                    int id = Client.Id;

                    string[] name = Request["GName"].Split(',').ToArray();
                    int[] deptid = Request["GDepartmentId"].Split(',').Select(x => Convert.ToInt32(x)).ToArray();
                    int[] desiid = Request["GDesignationId"].Split(',').Select(x => Convert.ToInt32(x)).ToArray();
                    string[] email = Request["GEmail"].Split(',').ToArray();
                    string[] mobile = Request["GContactNo"].Split(',').ToArray();
                    string[] whatsapp = Request["GWhatsAppNo"].Split(',').ToArray();

                    List<ContactPerson> contacts = new List<ContactPerson>();
                    for (int i = 0; i < name.Length; i++)
                    {
                        ContactPerson contactPerson = new ContactPerson
                        {
                            ClientId = id,
                            Name = name[i],
                            DepartmentId = deptid[i],
                            DesignationId = desiid[i],
                            Email = email[i],
                            ContactNo = mobile[i],
                            WhatsAppNo = whatsapp[i]
                        };
                        contacts.Add(contactPerson);
                    }
                    db.ContactPerson.AddRange(contacts);
                    db.SaveChanges();
                    TempData["msg"] = "1";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["Msg"] = MyFunctions.HandleMyError(ex);
                    return View(Client);
                }

            }
            return View(Client);
        }
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client Client = db.Client.Find(id);
            if (Client == null)
            {
                return HttpNotFound();
            }
            return View(Client);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Client Client, string DeletedIds)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(Client).State = EntityState.Modified;
                    db.SaveChanges();

                    int ClientId = Client.Id;

                    int[] Id = Request["GId"].Split(',').Select(x => Convert.ToInt32(x)).ToArray();

                    string[] name = Request["GName"].Split(',').ToArray();
                    int[] deptid = Request["GDepartmentId"].Split(',').Select(x => Convert.ToInt32(x)).ToArray();
                    int[] desiid = Request["GDesignationId"].Split(',').Select(x => Convert.ToInt32(x)).ToArray();
                    string[] email = Request["GEmail"].Split(',').ToArray();
                    string[] mobile = Request["GContactNo"].Split(',').ToArray();
                    string[] whatsapp = Request["GWhatsAppNo"].Split(',').ToArray();

                    for (int i = 0; i < Id.Length; i++)
                    {
                        AllProcs.AddUpdateContactPerson(Id[i], ClientId, name[i], desiid[i], deptid[i], email[i], mobile[i], whatsapp[i]);
                    }

                    if (!string.IsNullOrEmpty(DeletedIds))
                    {
                        AllProcs.DeleteContactPersons(DeletedIds);
                    }

                    TempData["Msg"] = "2";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["Msg"] = MyFunctions.HandleMyError(ex);
                    return View(Client);
                }
                
            }
            return View(Client);
        }
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Client Client = db.Client.Find(id);
        //    if (Client == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(Client);
        //}

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Client Client = db.Client.Find(id);
        //    db.Client.Remove(Client);
        //    db.SaveChanges();
        //    TempData["Msg"] = "3";
        //    return RedirectToAction("Index");
        //}

        public string StateChoice(int? Cid)
        {
            return JsonConvert.SerializeObject(AllProcs.StateChoice(Cid));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Clients/Delete.cshtml
@model EduCare.Models.Client

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClientBasicDetails</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Branch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pincode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Clients/Details.cshtml
@model EduCare.Models.ClientView

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    System.Data.DataTable getcontactperson = EduCare.Models.AllProcs.GetContactPerson(Model.Id);
    System.Data.DataTable country = EduCare.Models.AllProcs.GetCountry();
    System.Data.DataTable state = EduCare.Models.AllProcs.GetState();
}

<h4 class="fw-bold mt-3 mb-3"><a href=@Url.Action("Index","Clients") class="back-btn"><i class="fa fa-arrow-left"></i> Client Details</a></h4>

<div class="box box-primary">
    <div class="box-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>

                        <dd>
                            : @Html.DisplayFor(model => model.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Branch)
                        </dt>

                        <dd>
                            : @Html.DisplayFor(model => model.Branch)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ContactNo)
                        </dt>

                        <dd>
                            : @Html.DisplayFor(model => model.ContactNo)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Email)
                        </dt>

                        <dd>
                            : @Html.DisplayFor(model => model.Email)
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Address)
                        </dt>

                        <dd>
                            : @Html.DisplayFor(model => model.Address)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CountryId)
                        </dt>

                        <dd>
                            : @Model.Country
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.StateId)
                        </dt>

                        <dd>
                            : @Model.State
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.City)
                        </dt>

                        <dd>
                            : @Html.DisplayFor(model => model.City)
                        </dd>

                        <dt>
                            Pincode
                        </dt>

                        <dd>
                            : @Model.Pincode
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Website)
                        </dt>

                        <dd>
                            : @Html.DisplayFor(model => model.Website)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Status)
                        </dt>

                        <dd>
                            : @if (Model.Status ?? false)
                            {
                                <span class="label badge-soft-success">Active</span>
                            }
                            else
                            {
                                <span class="label badge-soft-danger">Inactive</span>
                            }
                        </dd>

                    </dl>
                </div>
            </div>
        </div>

        <h4>CONTACT PERSON</h4>
        <hr />
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group table-responsive">
                    <table class="table table-bordered  table-condensed text-center text-nowrap">
                        <thead style="background-color:#d7d7d7">
                            <tr>
                                <th>Sno.</th>
                                <th>Name</th>
                                <th>Department</th>
                                <th>Designation</th>
                                <th>Email</th>
                                <th>Contact No.</th>
                                <th>WhatsApp No.</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < getcontactperson.Rows.Count; i++)
                            {
                                <tr>

                                    <td>@(i+1)</td>
                                    <td>@getcontactperson.Rows[i]["Name"].ToString()</td>
                                    <td>@getcontactperson.Rows[i]["Department"].ToString()</td>
                                    <td>@getcontactperson.Rows[i]["Designation"].ToString()</td>
                                    <td>@getcontactperson.Rows[i]["Email"].ToString()</td>
                                    <td>@getcontactperson.Rows[i]["ContactNo"].ToString()</td>
                                    <td>@getcontactperson.Rows[i]["WhatsAppNo"].ToString()</td>
                                </tr>

                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>


        <h4>BILLING DETAILS</h4>
        <hr />
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <dl class="dl-horizontal">
                        <dt>
                            Billing Address
                        </dt>
                        <dd>
                            : @Model.BillingAddress
                        </dd>
                        <dt>
                            Country
                        </dt>
                        <dd>
                            : @Model.BillingCountryName
                        </dd>
                        <dt>
                            State
                        </dt>
                        <dd>
                            : @Model.BillingStateName
                        </dd>
                        <dt>
                            City
                        </dt>
                        <dd>
                            : @Model.BillingCity
                        </dd>
                        <dt>
                            Pin
                        </dt>
                        <dd>
                            : @Model.BillingPincode
                        </dd>

                    </dl>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <dl class="dl-horizontal">
                        <dt>
                            Email
                        </dt>
                        <dd>
                            : @Model.BillingEmail
                        </dd>
                        <dt>
                            PhoneNo.
                        </dt>
                        <dd>
                            : @Model.BillingPhoneNo
                        </dd>
                        <dt>
                            GST No.
                        </dt>
                        <dd>
                            : @Model.GSTNo
                        </dd>
                        <dt>
                            Payment Terms
                        </dt>
                        <dd>
                            : @Model.PaymentTerms
                        </dd>
                        <dt>
                            Terms & Conditions.
                        </dt>
                        <dd>
                            : @Model.TAndC
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="float-end">
            <a type="button" href="@Url.Action("Index","Clients")" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
        </div>
    </div>
</div>

Views/Clients/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    System.Data.DataTable dt = EduCare.Models.AllProcs.GetTableData("Client");
    var s = TempData["Msg"];
    if (s == null)
    {
        s = 0;
    }
}
<div class="msg-alert">
    @if (s.ToString() == "2")
    {
        <div class="alert alert-warning alert-dismissible" style="background-color: #e5bb79!important">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="color: white; opacity: 1; font-size: 25px;">×</button>
            Data Updated!
        </div>
    }
    else if (s.ToString() == "3")
    {
        <div class="alert alert-danger alert-dismissible" style="background-color: #cd6f64!important;">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="color: white; opacity: 1; font-size: 25px;">×</button>
            Data Deleted!
        </div>
    }
    else if (s.ToString() == "1")
    {
        <div class="alert alert-success alert-dismissible" style="background-color: #4da97f!important">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="color: white; opacity: 1; font-size: 25px;">×</button>
            Data Saved!
        </div>
    }
</div>
<h3 class="fw-bold" style="margin-top:0;">Clients</h3>


<div class="box box-primary">
    <div class="box-body">

        <div class="row">
            <div class="col-sm-3">
                <div class="form-group">
                    <a type="button" href="@Url.Action("Create","Clients")" class="btn btn-default">Add Client</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="form-group table-responsive">
                    <table class="table table-bordered table-condensed table-striped text-nowrap myDataTable text-center">
                        <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>
                                    Client
                                </th>
                                <th>
                                    Branch
                                </th>
                                <th>
                                    ContactNo.
                                </th>
                                <th>
                                    Status
                                </th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < dt.Rows.Count; i++)
                            {
                                int id = Convert.ToInt32(dt.Rows[i]["Id"].ToString());
                                <tr>
                                    <td>@(i+1)</td>
                                    <td>
                                        @dt.Rows[i]["Name"].ToString()
                                    </td>
                                    <td>
                                        @dt.Rows[i]["Branch"].ToString()
                                    </td>
                                    <td>
                                        @dt.Rows[i]["ContactNo"].ToString()
                                    </td>

                                    <td>
                                        @if (Convert.ToBoolean(dt.Rows[i]["Status"].ToString()))
                                        {
                                            <span class="label badge-soft-success">Active</span>
                                        }
                                        else
                                        {
                                            <span class="label badge-soft-danger">Inactive</span>
                                        }
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Clients", new { id = id})"><i class="fa fa-edit bg-warning"></i></a>
                                        <a href="@Url.Action("Details", "Clients", new { id = id})"><i class="fa fa-eye bg-success"></i></a>
                                        @*<a href="@Url.Action("Delete", "Clients", new { id = id})"><i class="fa fa-trash bg-danger"></i></a>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>