Models/University.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EduCare.Models
{
    [Table("University")]
    public class University
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public bool? Status { get; set; }
    }
}

Controllers/UniversitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EduCare.Models;

namespace EduCare.Controllers
{
    public class UniversitiesController : Controller
    {
        private EducareContext db = new EducareContext();

        // GET: Universities
        public ActionResult Index()
        {
            return View();
        }

        // GET: Universities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            University university = db.Universities.Find(id);
            if (university == null)
            {
                return HttpNotFound();
            }
            return View(university);
        }

        // GET: Universities/Create
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( University university)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    university.Status = true;
                    db.Universities.Add(university);
                    db.SaveChanges();
                    TempData["Msg"] = "1";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["Msg"] = MyFunctions.HandleMyError(ex);
                    return View(university);
                }
                
            }

            return View(university);
        }

        // GET: Universities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            University university = db.Universities.Find(id);
            if (university == null)
            {
                return HttpNotFound();
            }
            return View(university);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(University university)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(university).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["Msg"] = "2";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["Msg"] = MyFunctions.HandleMyError(ex);
                    return View(university);
                }
                
            }
            return View(university);
        }

        // GET: Universities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            University university = db.Universities.Find(id);
            if (university == null)
            {
                return HttpNotFound();
            }
            return View(university);
        }

        // POST: Universities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            University university = db.Universities.Find(id);
            db.Universities.Remove(university);
            db.SaveChanges();
            TempData["Msg"] = "3";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Universities/Create.cshtml
@model EduCare.Models.University

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold mt-3 mb-3"><a href=@Url.Action("Index","Universities") class="back-btn"><i class="fa fa-arrow-left"></i> Create University</a></h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="box box-primary small-card">
        <div class="box-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label label-required" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "University", @required = "required" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    
}

Views/Universities/Delete.cshtml
@model EduCare.Models.University

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold mt-3 mb-3"><a href=@Url.Action("Index","Universities") class="back-btn"><i class="fa fa-arrow-left"></i> Delete University</a></h4>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="box box-primary small-card">
        <div class="box-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                : @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Status)
                            </dt>

                            <dd>
                                : @if (Model.Status ?? false)
                                {


                                    <span class="label badge-soft-success">Active</span>
                                }
                                else
                                {
                                    <span class="label badge-soft-danger">Inactive</span>
                                }
                            </dd>

                        </dl>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




}

Views/Universities/Details.cshtml
@model EduCare.Models.University

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold mt-3 mb-3"><a href=@Url.Action("Index","Universities") class="back-btn"><i class="fa fa-arrow-left"></i> University Details</a></h4>

<div class="box box-primary small-card">
    <div class="box-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>

                        <dd>
                            : @Html.DisplayFor(model => model.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Status)
                        </dt>

                        <dd>
                            : @if (Model.Status ?? false)
                            {


                                <span class="label badge-soft-success">Active</span>
                            }
                            else
                            {
                                <span class="label badge-soft-danger">Inactive</span>
                            }
                        </dd>

                    </dl>
                </div>
            </div>
        </div>
    </div>

</div>

Views/Universities/Edit.cshtml
@model EduCare.Models.University

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold mt-3 mb-3"><a href=@Url.Action("Index","Universities") class="back-btn"><i class="fa fa-arrow-left"></i> Edit University</a></h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="box box-primary small-card">
        <div class="box-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label label-required" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
                        <select id="Status" name="Status" class="form-control">
                            <option value="True">Active</option>
                            <option value="False">Inactive</option>
                        </select>
                        <script>$('#Status').val('@Model.Status')</script>
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    
}

Views/Universities/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    System.Data.DataTable dt = EduCare.Models.AllProcs.GetTableData("University");
    var s = TempData["Msg"];
    if (s == null)
    {
        s = 0;
    }
}

<div class="msg-alert">
    @if (s.ToString() == "1")
    {
        <div class="alert alert-success alert-dismissible" style="background-color: #4da97f!important">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="color: white; opacity: 1; font-size: 25px;">×</button>
            Data Saved!
        </div>
    }
    else if (s.ToString() == "2")
    {
        <div class="alert alert-warning alert-dismissible" style="background-color: #e5bb79!important">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="color: white; opacity: 1; font-size: 25px;">×</button>
            Data Updated!
        </div>
    }
    else if (s.ToString() == "3")
    {
        <div class="alert alert-danger alert-dismissible" style="background-color: #cd6f64!important;">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="color: white; opacity: 1; font-size: 25px;">×</button>
            Data Deleted!
        </div>
    }
</div>

<h3 class="fw-bold" style="margin-top:0;">Universities</h3>


<div class="box box-primary">
    <div class="box-body">

        <div class="row">
            <div class="col-sm-3">
                <div class="form-group">
                    <a type="button" href="@Url.Action("Create","Universities")" class="btn btn-default">Add University</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="form-group table-responsive">
                    <table class="table table-striped table-condensed text-center myDataTable text-nowrap">
                        <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Status
                                </th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < dt.Rows.Count; i++)
                            {
                                int id = Convert.ToInt32(dt.Rows[i]["Id"].ToString());
                                <tr>
                                    <td>@(i+1)</td>
                                    <td>
                                        @dt.Rows[i]["Name"].ToString()
                                    </td>
                                    <td>
                                        @if (Convert.ToBoolean(dt.Rows[i]["Status"].ToString()))
                                        {
                                            <span class="label badge-soft-success">Active</span>
                                        }
                                        else
                                        {
                                            <span class="label badge-soft-danger">Inactive</span>
                                        }
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Universities", new { id = id})"><i class="fa fa-edit bg-warning"></i></a>
                                        <a href="@Url.Action("Details", "Universities", new { id = id})"><i class="fa fa-eye bg-success"></i></a>
                                        <a href="@Url.Action("Delete", "Universities", new { id = id})"><i class="fa fa-trash bg-danger"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>